### ISSUE TITLE
1.0 suggestions

### ISSUE THREAD

**Issue by TrySound** [haoxins/gulp-file-include#70]
- [ ] remove stream mode support;
- [ ] remove non-parentheses `if` syntax;
- [ ] search include file relatively, and in paths;
- [ ] parsing to ast
- [ ] make it async
- [ ] loop operator
- [ ] sourcemaps support

**Comment by TrySound** [comment]
@coderhaoxin We can make breaking changes before 1.0 release. 0.* is non-semver, so npm updates only patch version for this  ^0.*.*
So, it's nice ability to remove extra code.

**Comment by coderhaoxin** [comment]
@TrySound I think we could publish 1.0 now, and the todo list above should be 1.x.

**Comment by TrySound** [comment]
@coderhaoxin After 1.* couldn't have breaking changes. But here we can do them every 0.*

**Comment by coderhaoxin** [comment]
> After 1.* couldn't have breaking changes

Never mind, we could publish as 2.x, 3.x and so on.

**Comment by TrySound** [comment]
But still I want to make all cosmetic breaking changes before.

**Comment by TrySound** [comment]
It's nice solution with 0.*.

**Comment by TrySound** [comment]
However we can do no more releases before 1.0
